/* grammar-banks.js — original grammar MCQ banks. 12 topics × items.
   All items written originally for IELTS Score Accelerator. */
window.GRAMMAR_BANKS = {
  tenses: [
    {q:'"She ___ in London since 2015."', opts:['has lived','lives','lived'], a:0},
    {q:'"By the time we arrived, the film ___."', opts:['had started','started','starts'], a:0},
    {q:'"I ___ you tomorrow at the meeting."', opts:['will see','am seeing','see'], a:0},
    {q:'"This time next week, we ___ on a beach."', opts:['will be lying','will lie','are lying'], a:0},
    {q:'"He ___ TV when the phone rang."', opts:['was watching','watched','watches'], a:0},
    {q:'"Water ___ at 100°C."', opts:['boils','is boiling','boiled'], a:0},
  ],
  articles: [
    {q:'"She is ___ honest person."', opts:['an','a','the'], a:0},
    {q:'"___ Everest is the highest mountain."', opts:['—','The','A'], a:0},
    {q:'"I bought ___ umbrella yesterday."', opts:['an','a','the'], a:0},
    {q:'"___ Netherlands is famous for tulips."', opts:['The','—','A'], a:0},
    {q:'"He plays ___ guitar beautifully."', opts:['the','a','—'], a:0},
  ],
  conditionals: [
    {q:'"If I ___ rich, I would travel the world." (unreal present)', opts:['were','am','will be'], a:0},
    {q:'"If it rains, we ___ inside."', opts:['will stay','would stay','stayed'], a:0},
    {q:'"If she had studied, she ___ the exam."', opts:['would have passed','will pass','passed'], a:0},
    {q:'"I would help you if I ___ the answer."', opts:['knew','know','had known'], a:0},
    {q:'"Unless you hurry, you ___ the bus."', opts:['will miss','would miss','missed'], a:0},
  ],
  modals: [
    {q:'"You ___ be tired after such a long flight."', opts:['must','can','should'], a:0},
    {q:'"___ you mind opening the window?"', opts:['Would','Should','Could'], a:0},
    {q:'"She ___ have forgotten — she wrote it in her diary!"', opts:['can\'t','mustn\'t','shouldn\'t'], a:0},
    {q:'"You ___ see a doctor about that cough."', opts:['should','will','would'], a:0},
    {q:'"When I was young, I ___ swim every day."', opts:['used to','was used','would to'], a:0},
  ],
  passives: [
    {q:'"The bridge ___ in 1932."', opts:['was built','built','is built'], a:0},
    {q:'"English ___ all over the world."', opts:['is spoken','speaks','is speaking'], a:0},
    {q:'"The results ___ tomorrow."', opts:['will be announced','will announce','are announced'], a:0},
    {q:'"The house ___ at the moment."', opts:['is being painted','is painting','paints'], a:0},
    {q:'"He ___ to the party last week."', opts:['was invited','invited','is invited'], a:0},
  ],
  relatives: [
    {q:'"The book ___ I read last week was excellent."', opts:['that','who','whose'], a:0},
    {q:'"She is the artist ___ paintings won the prize."', opts:['whose','which','who\'s'], a:0},
    {q:'"The city ___ I was born has changed a lot."', opts:['where','which','when'], a:0},
    {q:'"My neighbour, ___ is a doctor, works nights."', opts:['who','which','that'], a:0},
    {q:'"2019 was the year ___ we moved here."', opts:['when','where','which'], a:0},
  ],
  gerunds: [
    {q:'"I enjoy ___ to podcasts on my way to work."', opts:['listening','to listen','listen'], a:0},
    {q:'"She decided ___ the job offer."', opts:['to accept','accepting','accept'], a:0},
    {q:'"He\'s good at ___ problems."', opts:['solving','to solve','solve'], a:0},
    {q:'"They suggested ___ the meeting until Monday."', opts:['postponing','to postpone','postpone'], a:0},
    {q:'"I\'m looking forward to ___ from you."', opts:['hearing','hear','have heard'], a:0},
  ],
  comparatives: [
    {q:'"This exercise is ___ than the last one."', opts:['much more difficult','much difficult','more much difficult'], a:0},
    {q:'"She runs ___ than her sister."', opts:['faster','more fast','fastly'], a:0},
    {q:'"It\'s ___ expensive restaurant in town." (superlative)', opts:['the most','most','the more'], a:0},
    {q:'"The ___ you practise, the better you get."', opts:['more','much','most'], a:0},
    {q:'"His handwriting is ___ than mine." (bad →)', opts:['worse','badder','worst'], a:0},
  ],
  prepositions: [
    {q:'"She apologised ___ being late."', opts:['for','of','about'], a:0},
    {q:'"He\'s married ___ a doctor."', opts:['to','with','by'], a:0},
    {q:'"The meeting depends ___ the weather."', opts:['on','of','in'], a:0},
    {q:'"I\'m not used ___ up early."', opts:['to waking','to wake','wake'], a:0},
    {q:'"They arrived ___ the airport at noon."', opts:['at','to','in'], a:0},
  ],
  reported: [
    {q:'"He said he ___ tired." (direct: "I am tired")', opts:['was','is','has been'], a:0},
    {q:'"She told me she ___ finish the report." (direct: "I will finish")', opts:['would','will','shall'], a:0},
    {q:'"They asked where I ___." (direct: "Where do you live?")', opts:['lived','live','do live'], a:0},
    {q:'"He ___ me not to worry."', opts:['told','said','spoke'], a:0},
    {q:'"She asked ___ I had seen the film."', opts:['whether','that','what'], a:0},
  ],
  quantifiers: [
    {q:'"There are ___ students in the hall." (many/much)', opts:['many','much','a lot'], a:0},
    {q:'"I don\'t have ___ money with me."', opts:['much','many','few'], a:0},
    {q:'"Only a ___ people attended." (small number)', opts:['few','little','lot'], a:0},
    {q:'"There is ___ hope of recovery." (uncountable, small)', opts:['little','few','a few'], a:0},
    {q:'"She has ___ friends in this city." (some, countable)', opts:['a few','a little','much'], a:0},
  ],
  wordorder: [
    {q:'Choose the correct order: ___', opts:['I have never been to Japan.','Never I have been to Japan.','I never have been to Japan.'], a:0},
    {q:'Choose the correct order: ___', opts:['She rarely eats fast food.','Rarely she eats fast food.','She eats rarely fast food.'], a:0},
    {q:'"Never ___ such a beautiful sunset."', opts:['have I seen','I have seen','I saw'], a:0},
    {q:'Choose the correct order: ___', opts:['What did you say that for?','For what you said that?','What for you said that?'], a:0},
    {q:'"Only later ___ the truth."', opts:['did he discover','he discovered','he did discover'], a:0},
  ],
};
