/* vocab-banks.js — original vocabulary MCQ banks per CEFR level.
   All items written originally for IELTS Score Accelerator (no copyrighted material). */
window.VOCAB_BANKS = {
  A1: [
    {q:'"Hello, ___ name is Sara." (my / me / I)', opts:['my','me','I'], a:0},
    {q:'A place where you borrow books is a ___.', opts:['library','kitchen','garage'], a:0},
    {q:'"What ___ is it? — It\'s 7 o\'clock."', opts:['time','hour','clock'], a:0},
    {q:'The opposite of "big" is ___.', opts:['small','tall','long'], a:0},
    {q:'You sleep in a ___.', opts:['bed','chair','table'], a:0},
    {q:'"She ___ to school every day."', opts:['goes','go','going'], a:0},
    {q:'A color: ___.', opts:['purple','apple','dog'], a:0},
    {q:'"I am hungry. I want some ___."', opts:['bread','water','air'], a:0},
    {q:'Monday, Tuesday, ___ …', opts:['Wednesday','Sunday','Friday'], a:0},
    {q:'"How ___ are you? — I\'m ten."', opts:['old','many','much'], a:0},
    {q:'The weather today is ___. The sun is shining.', opts:['sunny','rainy','windy'], a:0},
    {q:'"My father\'s mother is my ___."', opts:['grandmother','sister','aunt'], a:0},
    {q:'You use a ___ to write.', opts:['pen','cup','shoe'], a:0},
    {q:'"We eat breakfast in the ___."', opts:['morning','night','afternoon'], a:0},
    {q:'The opposite of "hot" is ___.', opts:['cold','warm','soft'], a:0},
    {q:'"Look! The baby ___ crying."', opts:['is','are','am'], a:0},
    {q:'A farm animal that gives milk: ___.', opts:['cow','horse','sheep'], a:0},
    {q:'"___ you like ice cream?" — "Yes, I do!"', opts:['Do','Does','Are'], a:0},
  ],
  A2: [
    {q:'"I\'m ___ in history — it\'s fascinating."', opts:['interested','interesting','interest'], a:0},
    {q:'"We ___ to the cinema last night."', opts:['went','go','gone'], a:0},
    {q:'A person who teaches is a ___.', opts:['teacher','student','doctor'], a:0},
    {q:'"Could you ___ me the salt, please?"', opts:['pass','take','bring'], a:0},
    {q:'The weather was terrible — it ___ all day.', opts:['rained','rain','raining'], a:0},
    {q:'"She speaks English ___ than her brother."', opts:['better','gooder','more good'], a:0},
    {q:'"I\'m going ___ holiday next week."', opts:['on','in','at'], a:0},
    {q:'"This book is ___ interesting than that one."', opts:['more','most','much'], a:0},
    {q:'You buy medicine at a ___.', opts:['pharmacy','bakery','library'], a:0},
    {q:'"Don\'t forget to ___ the lights before you leave."', opts:['turn off','turn on','open'], a:0},
    {q:'"He ___ his keys yesterday."', opts:['lost','losed','losing'], a:0},
    {q:'"Is there ___ milk in the fridge?"', opts:['any','some','many'], a:0},
    {q:'"I have lived here ___ 2019."', opts:['since','for','from'], a:0},
    {q:'A comfortable place to stay when travelling: a ___.', opts:['hotel','hospital','factory'], a:0},
    {q:'"The film starts ___ 8 p.m."', opts:['at','in','on'], a:0},
    {q:'"You ___ smoke here — it\'s forbidden."', opts:['mustn\'t','don\'t have','couldn\'t'], a:0},
    {q:'"She was tired, ___ she finished her homework."', opts:['but','so','because'], a:0},
    {q:'"I\'m looking forward to ___ you again."', opts:['seeing','see','saw'], a:0},
  ],
  B1: [
    {q:'"The company decided to ___ 50 new employees this year."', opts:['hire','rent','buy'], a:0},
    {q:'"He made a serious ___ in his calculation."', opts:['mistake','wrong','faulty'], a:0},
    {q:'"Global warming is one of the biggest ___ of our time."', opts:['challenges','challengers','changes'], a:0},
    {q:'"The government introduced a new ___ on plastic bags."', opts:['ban','band','bar'], a:0},
    {q:'"She ___ her success to hard work and patience."', opts:['owes','owns','earns'], a:0},
    {q:'"The lecture was so ___ that half the audience fell asleep."', opts:['dull','bored','boring'], a:2},
    {q:'"We need to find a ___ to this problem before Friday."', opts:['solution','solve','solvent'], a:0},
    {q:'"His attitude ___ me of my old boss."', opts:['reminds','remembers','reflects'], a:0},
    {q:'"The report ___ that air quality is improving."', opts:['suggests','suspects','supposes'], a:0},
    {q:'"I completely ___ with your point of view."', opts:['agree','accept','approve'], a:0},
    {q:'"Tourism has a significant ___ on the local economy."', opts:['impact','import','impress'], a:0},
    {q:'"She ___ the offer because the salary was too low."', opts:['turned down','turned up','turned on'], a:0},
    {q:'"The new law will ___ next month."', opts:['take effect','take part','take place'], a:0},
    {q:'" ___ the traffic, we arrived on time."', opts:['Despite','Although','However'], a:0},
    {q:'"Scientists have ___ a link between diet and sleep."', opts:['identified','invented','imagined'], a:0},
    {q:'"The project was completed ahead of ___."', opts:['schedule','time-table','plan'], a:0},
    {q:'"He\'s very ___ — he always arrives exactly when he says he will."', opts:['reliable','rely','reliant'], a:0},
    {q:'"Prices have risen ___ in the last year."', opts:['sharply','sharpen','sharpness'], a:0},
  ],
  B2: [
    {q:'"The findings are ___ with previous research in this field."', opts:['consistent','constant','persistent'], a:0},
    {q:'"The article ___ the causes of the economic decline."', opts:['examines','exercises','executes'], a:0},
    {q:'"There is growing ___ about the safety of the vaccine."', opts:['concern','concert','conduct'], a:0},
    {q:'"The two theories are ___ different."', opts:['fundamentally','fundamentals','foundations'], a:0},
    {q:'"She gave a very ___ answer — careful not to offend anyone."', opts:['diplomatic','diplomacy','diplomat'], a:0},
    {q:'"The study ___ a sample of 2,000 participants."', opts:['involved','included','contained','all'], a:0},
    {q:'"Urban ___ has transformed the city skyline."', opts:['expansion','expense','expedition'], a:0},
    {q:'"His argument was ___ — nobody could refute it."', opts:['compelling','compelled','compilation'], a:0},
    {q:'"The policy has ___ implications for small businesses."', opts:['far-reaching','far-going','far-fetching'], a:0},
    {q:'"Researchers ___ the data over a ten-year period."', opts:['analysed','announced','anticipated'], a:0},
    {q:'"The author ___ that reform is long overdue."', opts:['maintains','makes up','makes out'], a:0},
    {q:'"There is a ___ between diet and life expectancy."', opts:['correlation','correspondence','coordination'], a:0},
    {q:'"The speech was ___ received by the audience."', opts:['overwhelmingly','overwhelmed','overwhelming'], a:0},
    {q:'"We must ___ the risks before launching the product."', opts:['assess','access','assert'], a:0},
    {q:'"The novel provides a ___ into life in the 1920s."', opts:['glimpse','glance','review'], a:0},
    {q:'"Her research ___ existing assumptions about memory."', opts:['challenges','changes','charges'], a:0},
    {q:'"The committee reached a ___ after long debate."', opts:['consensus','census','senses'], a:0},
    {q:'"Economic growth has ___ over the past decade."', opts:['accelerated','celebrated','accumulated'], a:0},
  ],
};
